---
title: "GPpaymentGraphs"
output: word_document
date: "2025-10-15"
---

```{r load-imd}
library(tidyverse)
library(readxl)

# load IMD data and calculated a re-weighted IMD for 2021 LSOA codes using the 2011-2021 lookup

imd_raw <- read_csv(file="data/File_7_-_All_IoD2019_Scores__Ranks__Deciles_and_Population_Denominators_3.csv", name_repair = make.names)

#colnames(imd_raw)
imd <- imd_raw %>%
  rename(
    LSOA_CODE = LSOA.code..2011.,
    IMD_SCORE = Index.of.Multiple.Deprivation..IMD..Score,
    IMD_DECILE = Index.of.Multiple.Deprivation..IMD..Decile..where.1.is.most.deprived.10..of.LSOAs.,
    IMD_HEALTH = Health.Deprivation.and.Disability.Score) %>%
  mutate(
    IMD_QUINTILE = case_when(IMD_DECILE %in% c(1:2) ~ 1,
                             IMD_DECILE %in% c(3:4) ~ 2,
                             IMD_DECILE %in% c(5:6) ~ 3,
                             IMD_DECILE %in% c(7:8) ~ 4,
                             IMD_DECILE %in% c(9:10) ~ 5),
    LSOA_DATE = 2011) %>%
  select(LSOA_CODE, IMD_SCORE, IMD_HEALTH, IMD_QUINTILE, LSOA_DATE)

mapping <- read_csv(file = "data/LSOA_2011_to_LSOA_2021_Lookup_E_W.csv", name_repair = make.names)

# convert 2021 LSOA groups if the LSOA CHNGID M (merged in 2021) or X (unclear mapping)

weighted_mapping = mapping %>% left_join(
  mapping %>% filter(CHGIND=="M" | CHGIND=="X") %>%
    group_by(LSOA21CD) %>%
    summarise(WEIGHT=1/n())) %>%
  mutate(WEIGHT=if_else(CHGIND %in% c("S","U"),1,WEIGHT))


weighted_imd <- weighted_mapping  %>%
  left_join(select(imd, LSOA_CODE, IMD_HEALTH, IMD_SCORE), by=c("LSOA11CD" = "LSOA_CODE")) %>%
  mutate(
    weighted_imd = IMD_SCORE*WEIGHT,
    weighted_imd_health = IMD_HEALTH*WEIGHT
  ) %>%
  group_by(LSOA21CD) %>%
  summarise(
    IMD_SCORE = sum(weighted_imd),
    IMD_HEALTH = sum(weighted_imd_health)
  )  %>%
  mutate(IMD_QUINTILE = ntile(-IMD_SCORE,5)) %>%
  mutate(LSOA_DATE = 2021) %>%
  rename(LSOA_CODE = LSOA21CD)

imd_2011_2021 <- rbind(imd, weighted_imd)


year_list <- c(2017:2023)


load_ons_data <- function(year, sex) {
  
  #print(year)
  
  if(year == 2017) {
    object_url = "data/population/SAPE20DT2-mid-2017-lsoa-syoa-estimates-unformatted.xls"
  } else if(year == 2018) {
    object_url = "data/population/SAPE21DT2-mid-2018-lsoa-syoa-estimates-unformatted.xlsx"
  } else if(year == 2019) {
    object_url = "data/population/SAPE22DT2-mid-2019-lsoa-syoa-estimates-unformatted.xlsx"
  } else if(year == 2020) {
    object_url = "data/population/sape23dt2mid2020lsoasyoaestimatesunformatted.xlsx"
  } else if(year == 2021) {
    object_url = "data/population/sapelsoasyoatablefinal.xlsx"
    excel_sheet ="Mid-2021 LSOA 2021"
  } else if(year %in% c(2022:2023)) {
    object_url = "data/population/sapelsoasyoatablefinal.xlsx"
    excel_sheet ="Mid-2022 LSOA 2021"
  } # end setting the object url
  
  print(object_url)
  
  if(year == 2017) {
    
    lsoa_date = 2011
    
    data <- read_xls(
      path = object_url,
      sheet=paste0("Mid-",year," ",sex),
      skip = 4,
      trim_ws=TRUE,
      .name_repair = "universal"
    )
    
    # data <- aws.s3::s3read_using(
    #   FUN = readxl::read_xls,
    #   object = object_url,
    #   bucket = s3_bucket,
    #   sheet=paste0("Mid-",year," ",sex),
    #   skip = 4,
    #   trim_ws=TRUE,
    #   .name_repair = "universal")
    
  } else if(year %in% c(2018:2020)) {
    
    lsoa_date = 2011
    
    data <- read_xlsx(
      path = object_url,
      sheet = paste0("Mid-",year," ",sex),
      skip = 4,
      trim_ws=TRUE,
      .name_repair = "universal"
    )
    
    # data <- aws.s3::s3read_using(
    #   FUN = readxl::read_xlsx,
    #   object = object_url,
    #   bucket = s3_bucket,
    #   sheet=paste0("Mid-",year," ",sex),
    #   skip = 4,
    #   trim_ws=TRUE,
    #   .name_repair = "universal")
    
  } else if(year %in% c(2021:2023)) {
    
    lsoa_date = 2021
    
    data <- read_xlsx(
      path = object_url,
      sheet = excel_sheet,
      skip = 3,
      trim_ws=TRUE,
      .name_repair = "universal"
    )
    
    # data <- aws.s3::s3read_using(
    #   FUN = readxl::read_xlsx,
    #   object = object_url,
    #   bucket = s3_bucket,
    #   sheet = "Mid-2021 LSOA 2021",
    #   skip = 3,
    #   trim_ws=TRUE,
    #   .name_repair = "universal")
    
  } # end loading the data
  
  if(year %in% c(2017:2018)) {
    
    data1 <- data %>%
      select(-All.Ages) %>%
      pivot_longer(cols=!c('Area.Codes', 'Area.Names'), names_to='AGE', values_to='POP') %>%
      mutate(AGE = as.numeric(str_remove_all(AGE, '[^[:alnum:]]')),
             SEX = sex) %>%
      rename(LSOA_CODE = Area.Codes)
    
  } else if(year %in% c(2019:2020)) {
    
    data1 <- data %>%
      select(-contains('Boundaries'), -All.Ages) %>%
      pivot_longer(cols=!c('LSOA.Code', 'LSOA.Name'), names_to='AGE', values_to='POP') %>%
      mutate(AGE = as.numeric(str_remove_all(AGE, '[^[:alnum:]]')),
             SEX = sex) %>%
      rename(LSOA_CODE = LSOA.Code)
    
  } else if (year %in% c(2021:2023)) {
    
    data1 <- data %>%
      select(-c(LAD.2021.Code, LAD.2021.Name, LSOA.2021.Name, Total)) %>%
      pivot_longer(!LSOA.2021.Code, names_to="AGE", values_to="POP") %>%
      separate(AGE, into = c("SEX", "AGE"), sep = "(?<=[A-Za-z])(?=[0-9])") %>%
      mutate(SEX = case_when(SEX == "F" ~ "Females",SEX == "M" ~ "Males")
      ) %>%
      filter(SEX == sex) %>%
      rename(LSOA_CODE = LSOA.2021.Code)
    
  } # end cleaning the data by year
  
  # group into age groups once here
  data2 <- data1 %>%
    mutate(
      AGE = as.numeric(AGE),
      AGE = case_when(
        AGE %in% c(0:4) ~ "0_4",
        AGE %in% c(5:14) ~ "5_14",
        AGE %in% c(15:44) ~ "15_44",
        AGE %in% c(45:64) ~ "45_64",
        AGE %in% c(65:74) ~ "65_74",
        AGE %in% c(75:84) ~ "75_84",
        AGE >85  ~ "85_PLUS")
    ) %>%
    group_by(LSOA_CODE, AGE) %>%
    summarise(Total_POP = sum(POP)) %>%
    mutate(
      YEAR = year,
      SEX = sex,
      LSOA_DATE = lsoa_date
    )
  
}

#ons_data_M <- lapply(year_list, load_ons_data, sex="Males")
#ons_data_F <- lapply(year_list, load_ons_data, sex="Females")

#ons_both <- c(ons_data_M, ons_data_F)
ons_df <- read.csv("ons_population.csv", stringsAsFactors = FALSE)

#ons_df <- as.data.frame(do.call(rbind, ons_both))

## calculate weighted LSOA populations using Carr Hill formula values from 'Level or not?'

adj_pop_df <- ons_df %>%
  mutate(
    SEX = case_when(
      SEX == "Males" ~ "MALE",
      SEX == "Females" ~ "FEMALE"
    ),
    YEAR = as.numeric(YEAR)
  ) %>%
  pivot_wider(
    names_from = c(SEX, AGE),
    values_from = Total_POP
  ) %>%
  filter(!str_detect(LSOA_CODE, 'W')) %>%
  left_join(imd_2011_2021, by=c("LSOA_CODE"="LSOA_CODE", "LSOA_DATE"="LSOA_DATE")) %>%
  group_by(YEAR, LSOA_CODE) %>%
  mutate(TOTAL_POP = MALE_0_4 + 
           MALE_5_14 + 
           MALE_15_44 + 
           MALE_45_64 +
           MALE_65_74 +
           MALE_75_84 +
           MALE_85_PLUS +
           FEMALE_0_4 +
           FEMALE_5_14 +
           FEMALE_15_44 +
           FEMALE_45_64 +
           FEMALE_65_74 +
           FEMALE_75_84 +
           FEMALE_85_PLUS,
         ADJUSTED_POP = (2.354*MALE_0_4 + 
                           1*MALE_5_14 + 
                           0.913*MALE_15_44 + 
                           1.373*MALE_45_64 +
                           2.531*MALE_65_74 +
                           3.254*MALE_75_84 +
                           3.193*MALE_85_PLUS +
                           2.241*FEMALE_0_4 +
                           1.030*FEMALE_5_14 +
                           1.885*FEMALE_15_44 +
                           2.115*FEMALE_45_64 +
                           2.820*FEMALE_65_74 +
                           3.301*FEMALE_75_84 +
                           3.090*FEMALE_85_PLUS)* 1.054^IMD_HEALTH
         
  )

# normalise the adjusted population

adj_pop_norm = adj_pop_df %>% 
  group_by(YEAR) %>%
  summarise(TOTAL = sum(TOTAL_POP), ADJ=sum(ADJUSTED_POP)) %>%
  mutate(AF=TOTAL/ADJ) %>%
  select(YEAR,AF) %>%
  inner_join(adj_pop_df) %>%
  mutate(NORMALISED_ADJ_POP = ADJUSTED_POP*AF) %>%
  select(YEAR,LSOA_CODE,NEED_ADJ_POP=NORMALISED_ADJ_POP,TOTAL_POP)

### load the attribution datasets ###

temp = list.files(path = "data/attribution", pattern="\\.csv$", full.names = TRUE)

lsoa_attributions <- lapply(temp, read.csv)

#lsoa_attributions <- bulk_import_csv_files(iau_bucket, attribution_prefix)

for (i in seq_along(lsoa_attributions)) {
  names(lsoa_attributions[[i]]) <- c("PUBLICATION","EXTRACT_DATE","PRACTICE_CODE","PRACTICE_NAME","LSOA_CODE","SEX","NUMBER_OF_PATIENTS")
}

lsoa_attributions_df <- as.data.frame(do.call(rbind, lsoa_attributions))

lsoa_prac_pc = lsoa_attributions_df %>%
  mutate(YEAR = as.numeric(str_sub(EXTRACT_DATE, start = -4))) %>%
  select(YEAR, PRACTICE_CODE, PRACTICE_NAME, LSOA_CODE, NUMBER_OF_PATIENTS) %>%
  group_by(PRACTICE_CODE, YEAR) %>%
  mutate(total_pat_in_practice = sum(NUMBER_OF_PATIENTS),
         pc = NUMBER_OF_PATIENTS / total_pat_in_practice) %>%
  select(-NUMBER_OF_PATIENTS, -total_pat_in_practice) %>%
  ungroup() %>%
  mutate(LSOA_DATE = case_when(YEAR<2021 ~ 2011,
                               YEAR>2020 ~2021))

# assign IMD at the practice level using the attributions dataset
prac_imd = lsoa_prac_pc %>% 
  inner_join(imd_2011_2021, by=c("LSOA_CODE", "LSOA_DATE")) %>% 
  inner_join(adj_pop_norm, by=c("LSOA_CODE", "YEAR")) %>%
  group_by(YEAR,PRACTICE_CODE) %>%
  summarise(IMD_SCORE_PROP=sum(pc*TOTAL_POP*IMD_SCORE), TOTAL_POP=sum(pc*TOTAL_POP)) %>% #calculates number of people with each IMD score
  mutate(IMD_SCORE=IMD_SCORE_PROP/TOTAL_POP) %>% #takes the average IMD score of all the people
  ungroup() %>%
  select(YEAR,PRACTICE_CODE,IMD_SCORE,TOTAL_POP)

prac_imd = prac_imd %>% 
  group_by(YEAR) %>%
  arrange(-IMD_SCORE) %>%
  mutate(CUM_POP = cumsum(TOTAL_POP), PROP = CUM_POP/max(CUM_POP),
         #IMD_DECILE=cut(PROP,10,labels=FALSE),
         IMD_QUINTILE = ntile(PROP,5)) %>%
  select(YEAR,PRACTICE_CODE,IMD_SCORE,IMD_QUINTILE)

lsoa_pc = lsoa_attributions_df %>%
  mutate(YEAR = as.numeric(str_sub(EXTRACT_DATE, start = -4))) %>%
  select(YEAR, LSOA_CODE) %>%
  group_by(YEAR) %>%
  ungroup() %>%
  mutate(LSOA_DATE = case_when(YEAR<2021 ~ 2011,
                               YEAR>2020 ~2021))

lsoa_imd = lsoa_pc %>% 
  inner_join(imd_2011_2021, by=c("LSOA_CODE", "LSOA_DATE")) %>% 
  inner_join(adj_pop_norm, by=c("LSOA_CODE", "YEAR")) %>%
  group_by(YEAR,LSOA_CODE) %>%
  ungroup() %>%
  select(YEAR,LSOA_CODE,IMD_SCORE, IMD_QUINTILE, TOTAL_POP, NEED_ADJ_POP)

LSOA_imd_totals <- lsoa_imd %>%
  group_by(YEAR, IMD_QUINTILE) %>%
  summarise(
    TOTAL_NEED_ADJ_POP = sum(NEED_ADJ_POP, na.rm = TRUE),
    .groups = "drop"
  )

```


```{r load-imd}

### load workforce datasets

temp_workforce = list.files(path = "data/workforce", pattern="\\.csv$", full.names = TRUE)

september_records <- temp_workforce %>% str_subset(pattern = "September")


workforce_datasets <-   lapply(
  september_records, function(x) {
    print(x)
    split_path = strsplit(x, " ")
    year = split_path[[1]][[6]]
    workforce <- read.csv(x)
    
    workkforce_relevant_cols <- workforce %>%
      select(PRAC_CODE, PRAC_NAME, TOTAL_GP_FTE, TOTAL_GP_EXTGL_FTE, TOTAL_GP_EXL_FTE, TOTAL_GP_RET_FTE, GP_SOURCE) %>%
      mutate(YEAR = as.numeric(year))
    
  }
)

workforce_df <- as.data.frame(do.call(rbind, workforce_datasets))


attribute_gps_to_lsoa <- lsoa_prac_pc %>%
  filter(!str_detect(LSOA_CODE, 'W|NO2011')) %>%
  inner_join(workforce_df, by=c("PRACTICE_CODE" = "PRAC_CODE", "YEAR" = "YEAR")) %>%
  mutate(
    YEAR = as.numeric(YEAR),
    TOTAL_GP_EXTGL_FTE = as.numeric(TOTAL_GP_EXTGL_FTE),
    TOTAL_GP_RET_FTE = as.numeric(TOTAL_GP_RET_FTE),
    pc_fte_gps = pc*(TOTAL_GP_EXTGL_FTE-TOTAL_GP_RET_FTE)
  ) %>%
  group_by(LSOA_CODE, YEAR) %>%
  summarise(gps_lsoa = sum(pc_fte_gps, na.rm=T)) %>%
  left_join(adj_pop_norm, by=c("LSOA_CODE"="LSOA_CODE", "YEAR"="YEAR")) %>%
  mutate(LSOA_DATE = case_when(YEAR %in% c(2017:2020) ~ 2011,
                               YEAR %in% c(2021:2023) ~ 2021)) %>%
  left_join(imd_2011_2021, by=c("LSOA_CODE"="LSOA_CODE", "LSOA_DATE"= "LSOA_DATE"))


workforce_imd <- attribute_gps_to_lsoa %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(total_gps = sum(gps_lsoa, na.rm=T),
            total_population = sum(NEED_ADJ_POP, na.rm=T)) %>%
  mutate(gps_per_pop = 100000*total_gps/total_population) %>%
  na.omit()

write.csv(workforce_imd, "workforce.csv")

```




```{r load-imd}

## finance datasets
#remove the 1 from the 19-20 dataset 
temp_finance <- list.files(path = "data/payments", pattern="\\.csv$", full.names = TRUE)

finance_datasets <- lapply(temp_finance, function(x) {
  message("Processing: ", x)
  
  # Extract year from filename
  year <- as.numeric(gsub(".*?([0-9]{2,4}).*", "\\1", x))
  if (year < 100) year <- 2000 + year  # Handle 2-digit years
  
  # Read CSV
  finances <- read.csv(x, stringsAsFactors = FALSE)
  names_lower <- tolower(names(finances))
  
  # Helper: safely extract column(s) if they exist
  safe_extract <- function(pattern) {
    idx <- grep(pattern, names_lower, ignore.case = TRUE)
    if (length(idx) > 0) finances[, idx[1], drop = TRUE] else NA
  }
  
  # Helper: safely convert numeric columns
  to_numeric <- function(x) as.numeric(gsub(",", "", x))
  
  # Define all target columns with patterns
  columns <- list(
    PRACTICE_CODE = "practice.code",
    CONTRACT_TYPE = "contract.type",
    WEIGHTED_PATIENTS = "number.of.weighted.patients",
    REGISTERED_PATIENTS = "number.of.registered.patients",
    PAYMENTS_MINUS_DEDUCTIONS = "total.nhs.payments.to.general.practice.minus.deductions",
    PAYMENTS = "total.nhs.payments.to.general.practice",
    TOTAL_PAYMENTS = "total.nhs.payments.to.general.practice.including.covid.and.pcn.payments",
    TOTAL_COVID_PAYMENTS = "total.covid.payments",
    TOTAL_PCN_PAYMENTS = "total.pcn.payments",
    PRESCRIBING_FEE = "prescribing.fee.payments",
    DISPENSING_FEE = "dispensing.fee.payments",
    REINBURSMENT_FEE = "reimbursement.of.drugs",
    OTHER_PAYMENTS = "other.payments",
    GLOBAL_SUM = "global.sum",
    MPIG = "mpig.correction.factor",
    IT = "information.management.and.technology",
    PMS_BALANCE = "balance.of.pms.expenditure",
    QOF_PAYMENT = "total.qof.payments",
    CHILD_VACCINE = "childhood.vaccination.and.immunisation.scheme",
    FLU_VACCINE = "influenza.and.pneumococcal.immunisations",
    ROTAVIRUS_VACCINE = "rotavirus.and.shingles.immunisation",
    PREMISES_PAYMENT = "premises.payments",
    COVID_IMMUN = "covid.immunisation",
    COVID_SUPPORT = "covid.support.and.expansion",
    LONG_COVID = "long.covid",
    ALCOHOL = "alcohol",
    GP_EXTENDED = "gp.extended.hours.access",
    FTDD = "facilitating.timely.diagnosis.and.support.for.people.with.dementia",
    IPOA = "improving.patient.online.access",
    LD = "learning.disabilities",
    MS = "minor.surgery",
    PP = "patient.participation",
    RCM = "remote.care.monitoring",
    RPCM = "risk.profiling.and.case.management",
    SFVP = "services.for.violent.patients",
    UA = "unplanned.admissions",
    TNES = "total.national.enhanced.services",
    TLES = "total.local.enhanced.services",
    NDES = "non.des.item.pneumococcal.vaccine",
    OOAIHUC = "out.of.area.in.hours.urgent.care",
    Meningitis = "meningitis",
    Pertussis = "pertussis",
    TLIS = "total.local.incentive.schemes",
    LIS = "local.incentive.schemes",
    WMS = "weight.management.service",
    MAR = "medical.assessment.reviews",
    Seniority = "seniority",
    DRSP = "doctors.retainer.scheme.payments",
    TLA = "total.locum.allowances",
    AC = "appraisal.costs",
    PCO = "pco.admin.other",
    GPFV = "general.practice.forward.view",
    GPT = "general.practice.transformation",
    WAF = "winter.access.fund",
    PSL = "prolonged.study.leave",
    AACIRL = "appraisal.*appraiser.costs.in.respect.of.locums",
    PCNP = "pcn.participation",
    PCNL = "pcn.leadership",
    PCNS = "pcn.support",
    PCNEHA = "pcn.extended.hours.access",
    PCNW = "pcn.workforce",
    PCNIIF = "pcn.investment.and.impact.fund",
    PCNCHP = "pcn.care.home.premium",
    PCNEA = "pcn.enhanced.access"
  )
  
  # Extract and combine into one data frame
  extracted <- lapply(columns, safe_extract)
  df <- as.data.frame(extracted, stringsAsFactors = FALSE)
  
  # Add year
  df$YEAR <- year
  
  # Convert numeric-like fields
  num_cols <- setdiff(names(df), c("PRACTICE_CODE", "CONTRACT_TYPE", "YEAR"))
  df[num_cols] <- lapply(df[num_cols], function(x) suppressWarnings(to_numeric(x)))
  
  return(df)
})

# Combine all years
finances_df <- bind_rows(finance_datasets)

finance_imd_TEST <- finances_df %>%
  left_join(prac_imd, by = c("YEAR", "PRACTICE_CODE")) 

#To see how many NA's there are by year
test <- finance_imd_TEST %>%
  group_by(YEAR) %>%
  summarise(
    NAs = sum(is.na(IMD_QUINTILE)),
    non_NAs = sum(!is.na(IMD_QUINTILE))
  )

test_IMD <- finance_imd_TEST %>%
  group_by(YEAR, IMD_QUINTILE) %>%
  summarise(
    non_NAs = sum(!is.na(IMD_QUINTILE)),
    n_NA = sum(is.na(IMD_QUINTILE))
  )
```



```{r load-imd}
finance_imd <- finances_df %>%
  left_join(prac_imd, by = c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(
    TOTAL_PAYMENTS = sum(
      PAYMENTS,
      na.rm = TRUE
    ),
    TOTAL_WEIGHTED = sum(WEIGHTED_PATIENTS, na.rm = TRUE),
    NUM_PRACTICES = n_distinct(PRACTICE_CODE)
  ) %>%
  mutate(PAYMENT_PER_WEIGHTED_PATIENT = TOTAL_PAYMENTS / TOTAL_WEIGHTED) %>%
  na.omit()

finance_imd_registered <- finances_df %>%
  mutate(YEAR = as.numeric(YEAR),
         REGISTERED_PATIENTS = as.numeric(REGISTERED_PATIENTS),
         PAYMENTS = as.numeric(PAYMENTS)) %>%
  left_join(prac_imd, by=c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(TOTAL_PAYMENTS = sum(PAYMENTS, na.rm=T),
            TOTAL_REGISTERED = sum(REGISTERED_PATIENTS, na.rm=T)) %>%
  mutate(PAYMENT_PER_REGISTERED_PATIENT = TOTAL_PAYMENTS/TOTAL_REGISTERED) %>%
  na.omit()

Total_Payments_GMS <- finances_df %>%
  filter(CONTRACT_TYPE == "GMS")%>%
  mutate(
    YEAR = as.numeric(YEAR),
    WEIGHTED_PATIENTS = as.numeric(WEIGHTED_PATIENTS),
    REGISTERED_PATIENTS = as.numeric(REGISTERED_PATIENTS),
    CHILD_VACCINE = as.numeric(CHILD_VACCINE),
    FLU_VACCINE = as.numeric(FLU_VACCINE),
    ROTAVIRUS_VACCINE = as.numeric(ROTAVIRUS_VACCINE),
    PRESCRIBING_FEE = as.numeric(PRESCRIBING_FEE),
    DISPENSING_FEE = as.numeric(DISPENSING_FEE),
    REINBURSMENT_FEE = as.numeric(REINBURSMENT_FEE),
    OTHER_PAYMENTS = as.numeric(OTHER_PAYMENTS),
    QOF_PAYMENT = as.numeric(QOF_PAYMENT),
    PREMISES_PAYMENT = as.numeric(PREMISES_PAYMENT),
    PAYMENTS = as.numeric(PAYMENTS),
    PRESCRIBING_FEE = as.numeric(PRESCRIBING_FEE),
    DISPENSING_FEE = as.numeric(DISPENSING_FEE),
    REINBURSMENT_FEE = as.numeric(REINBURSMENT_FEE),
    OTHER_PAYMENTS = as.numeric(OTHER_PAYMENTS),
    GLOBAL_SUM = as.numeric(GLOBAL_SUM),
    MPIG = as.numeric(MPIG),
    IT = as.numeric(IT),
    PMS_BALANCE = as.numeric(PMS_BALANCE),
    QOF_PAYMENT = as.numeric(QOF_PAYMENT),
    CHILD_VACCINE = as.numeric(CHILD_VACCINE),
    FLU_VACCINE = as.numeric(FLU_VACCINE),
    ROTAVIRUS_VACCINE = as.numeric(ROTAVIRUS_VACCINE),
    PREMISES_PAYMENT = as.numeric(PREMISES_PAYMENT),
    COVID_IMMUN = as.numeric(COVID_IMMUN),
    COVID_SUPPORT = as.numeric(COVID_SUPPORT),
    LONG_COVID = as.numeric(LONG_COVID),
    ALCOHOL = as.numeric(ALCOHOL),
    GP_EXTENDED = as.numeric(GP_EXTENDED),
    FTDD = as.numeric(FTDD),
    IPOA = as.numeric(IPOA),
    LD = as.numeric(LD),
    MS = as.numeric(MS),
    PP = as.numeric(PP),
    RCM = as.numeric(RCM),
    RPCM = as.numeric(RPCM),
    SFVP = as.numeric(SFVP),
    UA = as.numeric(UA),
    TNES = as.numeric(TNES),
    TLES = as.numeric(TLES),
    NDES = as.numeric(NDES),
    OOAIHUC = as.numeric(OOAIHUC),
    Meningitis = as.numeric(Meningitis),
    Pertussis = as.numeric(Pertussis),
    TLIS = as.numeric(TLIS),
    LIS = as.numeric(LIS),
    WMS = as.numeric(WMS),
    MAR = as.numeric(MAR),
    Seniority = as.numeric(Seniority),
    DRSP = as.numeric(DRSP),
    TLA = as.numeric(TLA),
    AC = as.numeric(AC),
    PCO = as.numeric(PCO),
    GPFV = as.numeric(GPFV),
    GPT = as.numeric(GPT),
    WAF = as.numeric(WAF),
    PSL = as.numeric(PSL),
    AACIRL = as.numeric(AACIRL),
    PCNP = as.numeric(PCNP),
    PCNL = as.numeric(PCNL),
    PCNS = as.numeric(PCNS),
    PCNEHA = as.numeric(PCNEHA),
    PCNW = as.numeric(PCNW),
    PCNIIF = as.numeric(PCNIIF),
    PCNCHP = as.numeric(PCNCHP),
    PCNEA = as.numeric(PCNEA),
    GLOBAL_SUM_TOTAL = rowSums(across(c(GLOBAL_SUM, MPIG, PMS_BALANCE)), na.rm = TRUE),
    ITPremises = rowSums(across(c(PREMISES_PAYMENT, IT)), na.rm = TRUE),
    PCO = rowSums(across(c(Seniority, DRSP, TLA, AC, PCO, OTHER_PAYMENTS, GPFV, GPT, WAF, PSL, AACIRL,PCNP, PCNL, PCNS,  PCNEHA,  PCNW, PCNIIF, PCNCHP, PCNEA )), na.rm = TRUE),
    contractedServices  = rowSums(across(c(ALCOHOL, CHILD_VACCINE,GP_EXTENDED, FTDD, IPOA,FLU_VACCINE, LD,  MS,PP, RCM, RPCM, ROTAVIRUS_VACCINE, SFVP, UA,TNES,TLES,NDES, OOAIHUC, Meningitis, Pertussis, TLIS, LIS, WMS, MAR)), na.rm = TRUE),
    COVID  = rowSums(across(c(COVID_IMMUN,COVID_SUPPORT,LONG_COVID)), na.rm = TRUE),
    Prescribing   = rowSums(across(c(PRESCRIBING_FEE, DISPENSING_FEE, REINBURSMENT_FEE)), na.rm = TRUE)
  ) %>%
  left_join(prac_imd, by = c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(
    TOTAL_WEIGHTED = sum(WEIGHTED_PATIENTS, na.rm = TRUE),
    TOTAL_REGISTERED = sum(REGISTERED_PATIENTS, na.rm = TRUE),
    GLOBAL_SUM_TOTAL = sum(GLOBAL_SUM_TOTAL, na.rm = TRUE),
    IT_TOTAL = sum(ITPremises, na.rm = TRUE),
    QOF_PAYMENT_TOTAL = sum(QOF_PAYMENT, na.rm = TRUE),
    PCO_TOTAL = sum(PCO, na.rm = TRUE),
    contractedServices_TOTAL = sum(contractedServices, na.rm = TRUE),
    COVID_TOTAL = sum(COVID, na.rm = TRUE),
    Prescribing_TOTAL = sum(Prescribing, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_longer(
    cols = -c(YEAR, IMD_QUINTILE),
    names_to = "Variable",
    values_to = "Value"
  )

Total_Payments <- finances_df %>%
  mutate(
    YEAR = as.numeric(YEAR),
    WEIGHTED_PATIENTS = as.numeric(WEIGHTED_PATIENTS),
    REGISTERED_PATIENTS = as.numeric(REGISTERED_PATIENTS),
    CHILD_VACCINE = as.numeric(CHILD_VACCINE),
    FLU_VACCINE = as.numeric(FLU_VACCINE),
    ROTAVIRUS_VACCINE = as.numeric(ROTAVIRUS_VACCINE),
    PRESCRIBING_FEE = as.numeric(PRESCRIBING_FEE),
    DISPENSING_FEE = as.numeric(DISPENSING_FEE),
    REINBURSMENT_FEE = as.numeric(REINBURSMENT_FEE),
    OTHER_PAYMENTS = as.numeric(OTHER_PAYMENTS),
    QOF_PAYMENT = as.numeric(QOF_PAYMENT),
    PREMISES_PAYMENT = as.numeric(PREMISES_PAYMENT),
    PAYMENTS = as.numeric(PAYMENTS),
    PRESCRIBING_FEE = as.numeric(PRESCRIBING_FEE),
    DISPENSING_FEE = as.numeric(DISPENSING_FEE),
    REINBURSMENT_FEE = as.numeric(REINBURSMENT_FEE),
    OTHER_PAYMENTS = as.numeric(OTHER_PAYMENTS),
    GLOBAL_SUM = as.numeric(GLOBAL_SUM),
    MPIG = as.numeric(MPIG),
    IT = as.numeric(IT),
    PMS_BALANCE = as.numeric(PMS_BALANCE),
    QOF_PAYMENT = as.numeric(QOF_PAYMENT),
    CHILD_VACCINE = as.numeric(CHILD_VACCINE),
    FLU_VACCINE = as.numeric(FLU_VACCINE),
    ROTAVIRUS_VACCINE = as.numeric(ROTAVIRUS_VACCINE),
    PREMISES_PAYMENT = as.numeric(PREMISES_PAYMENT),
    COVID_IMMUN = as.numeric(COVID_IMMUN),
    COVID_SUPPORT = as.numeric(COVID_SUPPORT),
    LONG_COVID = as.numeric(LONG_COVID),
    ALCOHOL = as.numeric(ALCOHOL),
    GP_EXTENDED = as.numeric(GP_EXTENDED),
    FTDD = as.numeric(FTDD),
    IPOA = as.numeric(IPOA),
    LD = as.numeric(LD),
    MS = as.numeric(MS),
    PP = as.numeric(PP),
    RCM = as.numeric(RCM),
    RPCM = as.numeric(RPCM),
    SFVP = as.numeric(SFVP),
    UA = as.numeric(UA),
    TNES = as.numeric(TNES),
    TLES = as.numeric(TLES),
    NDES = as.numeric(NDES),
    OOAIHUC = as.numeric(OOAIHUC),
    Meningitis = as.numeric(Meningitis),
    Pertussis = as.numeric(Pertussis),
    TLIS = as.numeric(TLIS),
    LIS = as.numeric(LIS),
    WMS = as.numeric(WMS),
    MAR = as.numeric(MAR),
    Seniority = as.numeric(Seniority),
    DRSP = as.numeric(DRSP),
    TLA = as.numeric(TLA),
    AC = as.numeric(AC),
    PCO = as.numeric(PCO),
    GPFV = as.numeric(GPFV),
    GPT = as.numeric(GPT),
    WAF = as.numeric(WAF),
    PSL = as.numeric(PSL),
    AACIRL = as.numeric(AACIRL),
    PCNP = as.numeric(PCNP),
    PCNL = as.numeric(PCNL),
    PCNS = as.numeric(PCNS),
    PCNEHA = as.numeric(PCNEHA),
    PCNW = as.numeric(PCNW),
    PCNIIF = as.numeric(PCNIIF),
    PCNCHP = as.numeric(PCNCHP),
    PCNEA = as.numeric(PCNEA),
    GLOBAL_SUM_TOTAL = rowSums(across(c(GLOBAL_SUM, MPIG, PMS_BALANCE)), na.rm = TRUE),
    ITPremises = rowSums(across(c(PREMISES_PAYMENT, IT)), na.rm = TRUE),
    PCO = rowSums(across(c(Seniority, DRSP, TLA, AC, PCO, OTHER_PAYMENTS, GPFV, GPT, WAF, PSL, AACIRL,PCNP, PCNL, PCNS,  PCNEHA,  PCNW, PCNIIF, PCNCHP, PCNEA )), na.rm = TRUE),
    contractedServices  = rowSums(across(c(ALCOHOL, CHILD_VACCINE,GP_EXTENDED, FTDD, IPOA,FLU_VACCINE, LD,  MS,PP, RCM, RPCM, ROTAVIRUS_VACCINE, SFVP, UA,TNES,TLES,NDES, OOAIHUC, Meningitis, Pertussis, TLIS, LIS, WMS, MAR)), na.rm = TRUE),
    COVID  = rowSums(across(c(COVID_IMMUN,COVID_SUPPORT,LONG_COVID)), na.rm = TRUE),
    Prescribing   = rowSums(across(c(PRESCRIBING_FEE, DISPENSING_FEE, REINBURSMENT_FEE)), na.rm = TRUE)
  ) %>%
  left_join(prac_imd, by = c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(
    TOTAL_WEIGHTED = sum(WEIGHTED_PATIENTS, na.rm = TRUE),
    TOTAL_REGISTERED = sum(REGISTERED_PATIENTS, na.rm = TRUE),
    GLOBAL_SUM_TOTAL = sum(GLOBAL_SUM_TOTAL, na.rm = TRUE),
    IT_TOTAL = sum(ITPremises, na.rm = TRUE),
    QOF_PAYMENT_TOTAL = sum(QOF_PAYMENT, na.rm = TRUE),
    PCO_TOTAL = sum(PCO, na.rm = TRUE),
    contractedServices_TOTAL = sum(contractedServices, na.rm = TRUE),
    COVID_TOTAL = sum(COVID, na.rm = TRUE),
    Prescribing_TOTAL = sum(Prescribing, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  pivot_longer(
    cols = -c(YEAR, IMD_QUINTILE),
    names_to = "Variable",
    values_to = "Value"
  )

ADJ_pop <- attribute_gps_to_lsoa %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(total_gps = sum(gps_lsoa, na.rm=T),
            total_population = sum(NEED_ADJ_POP, na.rm=T)) %>%
  na.omit()

finance_ADJ <- finances_df %>%
  mutate(YEAR = as.numeric(YEAR),
         REGISTERED_PATIENTS = as.numeric(REGISTERED_PATIENTS),
         PAYMENTS = as.numeric(PAYMENTS)) %>%
  left_join(prac_imd, by=c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(TOTAL_PAYMENTS = sum(PAYMENTS, na.rm=T))  %>%
  na.omit()

finance_ADJ <- finance_ADJ %>%
  mutate(IMD_QUINTILE = as.character(IMD_QUINTILE)) %>%
  left_join(
    ADJ_pop %>%
      mutate(IMD_QUINTILE = as.character(IMD_QUINTILE)),
    by = c("YEAR", "IMD_QUINTILE")
  ) %>%
  mutate(
    PAYMENTS_PER_PERSON = TOTAL_PAYMENTS / total_population
  )

finance_imd_PaymentType <- Total_Payments %>%
  group_by(IMD_QUINTILE, YEAR) %>%
 # summarise(TOTAL_PAYMENTS = sum(PAYMENTS, na.rm=T),
 #           TOTAL_WEIGHTED = sum(WEIGHTED_PATIENTS, na.rm=T)) %>%
 # mutate(PAYMENT_PER_WEIGHTED_PATIENT = TOTAL_PAYMENTS/TOTAL_WEIGHTED) %>%
  na.omit()

Payments_per_weighted_patient <- Total_Payments_GMS %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  mutate(
    TOTAL_WEIGHTED = Value[Variable == "TOTAL_WEIGHTED"]
  ) %>%
  filter(Variable != "TOTAL_WEIGHTED", Variable != "TOTAL_REGISTERED") %>%
  mutate(
    PAYMENT_PER_WEIGHTED = Value / TOTAL_WEIGHTED
  ) %>%
  ungroup() %>%
  select(IMD_QUINTILE, YEAR, Variable, PAYMENT_PER_WEIGHTED)

Payments_per_registered_patient <- Total_Payments_GMS %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  # Get the total weighted patients for each group
  mutate(
    TOTAL_REGISTERED = Value[Variable == "TOTAL_REGISTERED"]
  ) %>%
  # Calculate payment per weighted patient for all other variables
  filter(Variable != "TOTAL_WEIGHTED", Variable != "TOTAL_REGISTERED") %>%
  mutate(
    PAYMENT_PER_REGISTERED = Value / TOTAL_REGISTERED
  ) %>%
  ungroup() %>%
  select(IMD_QUINTILE, YEAR, Variable, PAYMENT_PER_REGISTERED)

```

```{r myplot, fig.width=10, fig.height=6}

ggplot(finance_imd, aes(
  x = YEAR,
  y = PAYMENT_PER_WEIGHTED_PATIENT,
  color = as.factor(IMD_QUINTILE),
  group = IMD_QUINTILE
)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Set1", name = "IMD Quintile") +
  labs(
    title = "Payments per Weighted Patient by IMD Quintile",
    x = "Year",
    y = "Payment per Weighted Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )

ggplot(finance_imd_registered, aes(
  x = YEAR,
  y = PAYMENT_PER_REGISTERED_PATIENT,
  color = as.factor(IMD_QUINTILE),
  group = IMD_QUINTILE
)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Set1", name = "IMD Quintile") +
  labs(
    title = "Payments per REGISTERED Patient by IMD Quintile",
    x = "Year",
    y = "Payment per REGISTERED Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )

ggplot(finance_ADJ, aes(
  x = YEAR,
  y = PAYMENTS_PER_PERSON,
  color = as.factor(IMD_QUINTILE),
  group = IMD_QUINTILE
)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Set1", name = "IMD Quintile") +
  labs(
    title = "Payments per ADJ Patient by IMD Quintile",
    x = "Year",
    y = "Payment per ADJ Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )

plot_data_2023 <- Total_Payments %>%
  filter(
    YEAR == 2023,
    !is.na(IMD_QUINTILE),
    !Variable %in% c("TOTAL_WEIGHTED", "TOTAL_REGISTERED")
  )

ggplot(plot_data_2023, aes(
  x = as.factor(IMD_QUINTILE),
  y = Value,
  fill = Variable
)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3", name = "Payment Category") +
  labs(
    title = "Total NHS Payments by IMD Quintile (2023)",
    x = "IMD Quintile (1 = Most Deprived, 5 = Least Deprived)",
    y = "Total Payments (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 16)
  )

plot_data_2023_weighted <- Payments_per_weighted_patient %>%
  filter(
    YEAR == 2023,
    !is.na(IMD_QUINTILE),
    !Variable %in% c("TOTAL_WEIGHTED", "TOTAL_REGISTERED")
  )

ggplot(plot_data_2023_weighted, aes(
  x = as.factor(IMD_QUINTILE),
  y = PAYMENT_PER_WEIGHTED,
  fill = Variable
)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3", name = "Payment Category") +
  labs(
    title = "Average GP Payments per Weighted patients by IMD Quintile (2023) GMS only",
    x = "IMD Quintile (1 = Most Deprived, 5 = Least Deprived)",
    y = "Total Payments (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 16)
  )

plot_data_2023_registered <- Payments_per_registered_patient %>%
  filter(
    YEAR == 2023,
    !is.na(IMD_QUINTILE),
    !Variable %in% c("TOTAL_WEIGHTED", "TOTAL_REGISTERED")
  )

ggplot(plot_data_2023_registered, aes(
  x = as.factor(IMD_QUINTILE),
  y = PAYMENT_PER_REGISTERED,
  fill = Variable
)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3", name = "Payment Category") +
  labs(
    title = "Average GP Payments per Registered patients by IMD Quintile (2023) GMS only",
    x = "IMD Quintile (1 = Most Deprived, 5 = Least Deprived)",
    y = "Total Payments (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 16)
  )

```